# Generated by Django 4.2.6 on 2023-11-14 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountinfo_lattitude_accountinfo_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regtration_number', models.CharField(max_length=10, unique=True)),
                ('vehicle_brand', models.CharField(max_length=30)),
                ('vehicle_name', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('hatch', 'Hatchback')], max_length=20)),
                ('vehicle_color', models.CharField(max_length=30)),
                ('vehicle_year', models.DateField(blank=True, null=True)),
                ('insurance_end_date', models.DateField(blank=True, null=True)),
                ('license_validity', models.DateField(blank=True, null=True)),
                ('seat_capacity', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
