# Generated by Django 4.2.6 on 2023-11-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vehicleinfo_vehicle_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='vehicle_image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='vehicle_images/'),
        ),
    ]
