# Generated by Django 4.2.6 on 2023-11-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountinfo_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/download(2).png', null=True, upload_to='profile_images/'),
        ),
    ]
