# Generated by Django 4.2.6 on 2023-11-17 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
