# Generated by Django 4.2.6 on 2023-11-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountinfo_user_alter_vehicleinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinfo',
            old_name='regtration_number',
            new_name='registration_number',
        ),
    ]
