# Generated by Django 4.2.6 on 2023-11-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_regtration_number_vehicleinfo_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
