# Generated by Django 4.2.6 on 2023-11-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_lattitude_accountinfo_latitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='latitude',
            new_name='lattitude',
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
