# Generated by Django 4.2.6 on 2023-11-24 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_latitude_accountinfo_lattitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='about',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('about', models.TextField(blank=True, default=None, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('alternate_phone', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(blank=True, default='profile_images/download(2).png', null=True, upload_to='profile_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
