# Generated by Django 4.2.6 on 2023-11-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_activedrivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
