# Generated by Django 4.2.6 on 2023-11-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accountinfo_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activedrivers',
            name='existing_address',
        ),
    ]
