# Generated by Django 4.2.6 on 2023-11-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_activedrivers_existing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedrivers',
            name='existing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accountinfo'),
        ),
        migrations.AlterField(
            model_name='activedrivers',
            name='active_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicleinfo'),
        ),
    ]
