# Generated by Django 4.2.6 on 2023-11-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_activedrivers_existing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activedrivers',
            name='active_vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicleinfo'),
            preserve_default=False,
        ),
    ]
