# Generated by Django 4.2.6 on 2023-12-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_activedrivers_active_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinfo',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('hatch', 'Hatchback'), ('xuv', 'Xuv')], max_length=20),
        ),
    ]
