# Generated by Django 4.2.6 on 2023-12-14 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_vehicleinfo_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.DecimalField(decimal_places=20, max_digits=30)),
                ('start_long', models.DecimalField(decimal_places=20, max_digits=30)),
                ('end_lat', models.DecimalField(decimal_places=20, max_digits=30)),
                ('end_long', models.DecimalField(decimal_places=20, max_digits=30)),
                ('start_location_name', models.CharField(default=None, max_length=256, null=True)),
                ('end_location_name', models.CharField(default=None, max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('payafter', 'Payafter'), ('online', 'Online')], max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=256, null=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ride_vehicle', to='accounts.vehicleinfo')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_ride', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ride', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
