# Generated by Django 4.2.6 on 2023-12-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_transaction_id_trip_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='Vehicle',
        ),
    ]
