# Generated by Django 4.2.6 on 2023-12-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_trip_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ride_vehicle', to='accounts.vehicleinfo'),
            preserve_default=False,
        ),
    ]
