# Generated by Django 4.2.6 on 2023-12-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_trip_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Vehicle',
            new_name='vehicle',
        ),
    ]
